### ISSUE TITLE
switch to influx 1.0 RC1

### ISSUE THREAD

**Issue by francisdb** [waylayio/influxdb-scala#6]
https://influxdata.com/blog/announcing-influxdb-telegraf-kapacitor-and-enterprise-1-0-rc1/

**Comment by francisdb** [comment]
official docker image still missing
https://hub.docker.com/_/influxdb/

**Comment by gillesdemey** [comment]
Not required, since we're not running it on a Docker machine? Or is that an option we're exploring?

**Comment by pizuricv** [comment]
I would not bother since we are moving to another time series anyway

**Comment by francisdb** [comment]
tests run on a docker instance started during tests, currently 1.0 beta3
please refrain from adding waylay related comments, this is a open source, same for our kairosdb driver
